### PR TITLE
Extend README, remove duplicate const, lower feature level

### PR DESCRIPTION
**Pull request by mkovaxx**
- extended the README based on the problems I had
- added helper function for better error reporting
- removed duplicate `const` qualifier from a function argument
- lowered feature level to `D3D_FEATURE_LEVEL_11_0` (couldn't get `D3D_FEATURE_LEVEL_11_1` to work, even though I have the latest Windows SDK)

### CODE REVIEW

**Comment by jbfove** [comment]
Hi mkovacs,

Thanks this pull request :)

These are my only two concerns before pulling it:

1. After your rebase, only the readme changes remain: the const fix, feature level change, etc, are no longer present. Also the commit message simply reads "rebase against master" instead of having each original commit message with their descriptions. Can you retry your rebase (if you still have the original commits) without squashing?
2. The part you added to the readme about adding the FoveClient.dll path to the PATH environment variable is not needed. The cmake script has a bit at the end where it adds a post-build-script that copies the built-in FoveClient.dll to the executable output directory. If this is not working on your machine, I'd prefer to debug that rather than having users deal with the PATH. I just tested it out on my end and it appears to work, can you check if the FoveClient.dll file shows up next to the executable on your machine?

**Comment by mkovaxx** [comment]
Hi, thanks for taking a look!

1. Thanks for pointing this out. I didn't notice that I totally messed up that rebase. Fixed it just now.
2. If I don't have the location of FoveClient.dll in my PATH, then running the sample from inside Visual Studio fails with an error message saying that FoveClient.dll is missing from my computer. See screenshot below. That's why I think the README should recommend adding it to the PATH.

fove-dll-error

**Comment by jbfove** [comment]
Thanks for re-rebasing!

I pulled two of your commits:
remove duplicate const
lower feature level to D3D_FEATURE_LEVEL_11_0

For the error message, while your commit was mostly fine (other than a memory leak), I wanted to do a full pass on all the DX/WinAPI functions rather than just the single one you added.
https://github.com/FoveHMD/FoveCppSample/commit/fe04c86815409605ed43578a67d36b771a37af90
The "improve error message" commit is not needed after those changes.

Regarding the FoveClient.dll thing, I want to see if we can find the bug before moving forward with a workaround. The intended behavior is that a post-build script copies the FoveClient.dll into the executable directory. Windows will search the exe dir first, before searching the PATH, so the PATH thing is not needed, assuming the script ran. Can you paste the full path where the output executable was put by Visual studio, and can you check if the FoveClient.dll is there?

This is done by the following line in the cmake script:
add_custom_command(TARGET FoveDirectX11Example POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different "${FoveDLL}" $<TARGET_FILE_DIR:FoveDirectX11Example>)
Which generates a post-build-event in Visual Studio, which you can get to by right clicking on the FoveDirectX11Example target in the solution explorer, selecting Properties, then going to "Build Events"->"Post-Build Event". You should see a copy script in there, can you check that all of the paths are correct?

Thanks for your help,
Jeff

**Comment by mkovaxx** [comment]
Hey Jeff,

I think it's the `Run CMake to generate a 64-bit Visual Studio project.` step that throws my setup off.
Can you recommend a specific command to run for that step? (I've tried `cmake .` and `cmake . -DCMAKE_GENERATOR_PLATFORM=x64`, but ran into problems with both, and had to manually change things in Visual Studio, which is likely the source of the problem.)

Thanks,
Mate

**Comment by jbfove** [comment]
In cmake + visual studio, the generators are architecture specific, so I use the command:
```
cd path/to/BuildFolder
cmake -G "Visual Studio 14 2015 Win64" path/to/FoveCppSample
```

If you are using 2017, then it would be "Visual Studio 15 2017 Win64" (though we haven't tested this yet).

Let me know if this works for you and I'll update the documentation.

There is also a cmake GUI that comes with the Windows installer that may be easier to learn/use than the command line interface.

**Comment by mkovaxx** [comment]
`cmake -G "Visual Studio 14 2015 Win64" .` worked. I can verify that Visual Studio can run the executable without adding `FoveClient.dll` to the PATH. Thanks!

**Pull request closed without merging**
